/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.com.kamil.ociepa.kolkokrzyzyk;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import pl.com.kamil.ociepa.kolkokrzyzyk.gameutils.DrawPlayer;

/**
 *
 * @author a20ko
 */
public class GameWindow extends javax.swing.JFrame {
    private boolean player = false;
    private Player p1,p2;
    /**
     * Creates new form Okienko
     */
    public GameWindow() {
        initComponents();
        initGame();
        setCircleOrCrossToAllButtons();
        clearButtonText();
    }
    private void initGame(){
        
        player = DrawPlayer.randomPlayer();

        if(DrawPlayer.randomPlayer()){
            jLPlayer1.setBackground(Color.GREEN);
            jLPlayer2.setBackground(Color.GRAY);
        }else{
            jLPlayer2.setBackground(Color.GREEN);
            jLPlayer1.setBackground(Color.GRAY);
        }
        if(DrawPlayer.randomSign()){
            jLPlayer1Sign.setText("O");
            jLPlayer2Sign.setText("X");
            p1 = new Player("O",jTFPlayer1.getText());
            p2 = new Player("X",JTFPlayer2.getText());
        }else{
            jLPlayer2Sign.setText("O");
            jLPlayer1Sign.setText("X");
            p1 = new Player("O",jTFPlayer1.getText());
            p2 = new Player("X",JTFPlayer2.getText());
        }
        
            
    }
    
    private void setCircleOrCrossToAllButtons(){
        jB11.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setCircleOrCross(evt);
            }
        });
        jB12.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setCircleOrCross(evt);
            }
        });
        jB13.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setCircleOrCross(evt);
            }
        });
        jB21.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setCircleOrCross(evt);
            }
        });
        jB22.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setCircleOrCross(evt);
            }
        });
        jB23.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setCircleOrCross(evt);
            }
        });
        jB31.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setCircleOrCross(evt);
            }
        });
        jB32.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setCircleOrCross(evt);
            }
        });
        jB33.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setCircleOrCross(evt);
            }
        });
        
    }
    private void clearButtonText(){
        jB11.setText("");
        jB12.setText("");
        jB13.setText("");
        jB21.setText("");
        jB22.setText("");
        jB23.setText("");
        jB31.setText("");
        jB32.setText("");
        jB33.setText("");
    }
        
    private void setCircleOrCross(ActionEvent evt){
        JButton b = (JButton) evt.getSource();
        if(player){
            b.setText(p1.getSign());
        }else{
            b.setText(p2.getSign());
        }
        System.out.println(b.toString());
        player = !player;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRBPlayervsPlayer = new javax.swing.JRadioButton();
        jRBPlayervsComputer = new javax.swing.JRadioButton();
        jTFPlayer1 = new javax.swing.JTextField();
        JTFPlayer2 = new javax.swing.JTextField();
        jLPlayer1 = new javax.swing.JLabel();
        jLPlayer2 = new javax.swing.JLabel();
        jLPlayer1Sign = new javax.swing.JLabel();
        jLPlayer2Sign = new javax.swing.JLabel();
        jBRestetGame = new javax.swing.JButton();
        jB21 = new javax.swing.JButton();
        jB23 = new javax.swing.JButton();
        jB22 = new javax.swing.JButton();
        jB31 = new javax.swing.JButton();
        jB13 = new javax.swing.JButton();
        jB11 = new javax.swing.JButton();
        jB32 = new javax.swing.JButton();
        jB33 = new javax.swing.JButton();
        jB12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        buttonGroup1.add(jRBPlayervsPlayer);
        jRBPlayervsPlayer.setText("1 Gracz");
        jRBPlayervsPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPlayervsPlayerActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBPlayervsComputer);
        jRBPlayervsComputer.setSelected(true);
        jRBPlayervsComputer.setText("2 Graczy");

        jLPlayer1.setBackground(new java.awt.Color(204, 204, 255));
        jLPlayer1.setText("Gracz1");
        jLPlayer1.setOpaque(true);

        jLPlayer2.setBackground(new java.awt.Color(204, 204, 255));
        jLPlayer2.setText("Gracz2");
        jLPlayer2.setOpaque(true);

        jLPlayer1Sign.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLPlayer1Sign.setText("X");

        jLPlayer2Sign.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLPlayer2Sign.setText("O");

        jBRestetGame.setText("RESET");
        jBRestetGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRestetGameActionPerformed(evt);
            }
        });

        jB21.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        jB23.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        jB22.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        jB31.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        jB13.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        jB11.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        jB32.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        jB33.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        jB12.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRBPlayervsComputer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jRBPlayervsPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBRestetGame, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTFPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLPlayer1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLPlayer1Sign)
                        .addGap(62, 62, 62)
                        .addComponent(jLPlayer2Sign)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLPlayer2))))
                .addGap(255, 255, 255))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jB21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB31, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB22, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB23, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB32, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB33, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBPlayervsPlayer)
                    .addComponent(jRBPlayervsComputer)
                    .addComponent(jBRestetGame))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPlayer1)
                    .addComponent(jLPlayer2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPlayer1Sign)
                    .addComponent(jLPlayer2Sign))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB21, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB22, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB23, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB31, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB32, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB33, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBPlayervsPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPlayervsPlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBPlayervsPlayerActionPerformed

    private void jBRestetGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRestetGameActionPerformed
        initGame();
        clearButtonText();
    }//GEN-LAST:event_jBRestetGameActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFPlayer2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jB11;
    private javax.swing.JButton jB12;
    private javax.swing.JButton jB13;
    private javax.swing.JButton jB21;
    private javax.swing.JButton jB22;
    private javax.swing.JButton jB23;
    private javax.swing.JButton jB31;
    private javax.swing.JButton jB32;
    private javax.swing.JButton jB33;
    private javax.swing.JButton jBRestetGame;
    private javax.swing.JLabel jLPlayer1;
    private javax.swing.JLabel jLPlayer1Sign;
    private javax.swing.JLabel jLPlayer2;
    private javax.swing.JLabel jLPlayer2Sign;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBPlayervsComputer;
    private javax.swing.JRadioButton jRBPlayervsPlayer;
    private javax.swing.JTextField jTFPlayer1;
    // End of variables declaration//GEN-END:variables
}
