/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.com.kamil.ociepa.przeliczaniejednostek;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.*;

/**
 *
 * @author a20ko
 */
public class ZadanieKamilOciepa extends javax.swing.JFrame {

    /**
     * Creates new form ZadanieKamilOciepa
     */
    public ZadanieKamilOciepa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ko_jPanelGłówny = new javax.swing.JPanel();
        ko_jLabelPrzeliczanie = new javax.swing.JLabel();
        ko_jComboBoxPrzeliczanie = new javax.swing.JComboBox<>();
        ko_jLabelJednostki = new javax.swing.JLabel();
        ko_jTextFieldJednostka = new javax.swing.JTextField();
        ko_jLabelPrzeliczone = new javax.swing.JLabel();
        ko_jTextFieldPrzeliczone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ko_jTextAreaOdczyt = new javax.swing.JTextArea();
        ko_jMenuBarMenu = new javax.swing.JMenuBar();
        ko_jMenuPlik = new javax.swing.JMenu();
        ko_jMenuItemHistoria = new javax.swing.JMenuItem();
        ko_jMenuItemZamknij = new javax.swing.JMenuItem();
        ko_jMenuProgram = new javax.swing.JMenu();
        ko_jMenuItemProgram = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ko_jPanelGłówny.setBackground(new java.awt.Color(0, 153, 153));

        ko_jLabelPrzeliczanie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ko_jLabelPrzeliczanie.setText("Co chcesz przeliczyć?:");

        ko_jComboBoxPrzeliczanie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Temperatura", "Odległość" }));
        ko_jComboBoxPrzeliczanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_jComboBoxPrzeliczanieActionPerformed(evt);
            }
        });

        ko_jLabelJednostki.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ko_jLabelJednostki.setText("Wprowadź wartość którą chcesz przeliczyć (jednostka): ");

        ko_jTextFieldJednostka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_jTextFieldJednostkaActionPerformed(evt);
            }
        });

        ko_jLabelPrzeliczone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ko_jLabelPrzeliczone.setText("Przeliczona wartość (jednostka):");

        ko_jTextFieldPrzeliczone.setEditable(false);
        ko_jTextFieldPrzeliczone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_jTextFieldPrzeliczoneActionPerformed(evt);
            }
        });

        jLabel1.setText("Odczytane dane");

        ko_jTextAreaOdczyt.setEditable(false);
        ko_jTextAreaOdczyt.setColumns(20);
        ko_jTextAreaOdczyt.setRows(5);
        jScrollPane2.setViewportView(ko_jTextAreaOdczyt);

        javax.swing.GroupLayout ko_jPanelGłównyLayout = new javax.swing.GroupLayout(ko_jPanelGłówny);
        ko_jPanelGłówny.setLayout(ko_jPanelGłównyLayout);
        ko_jPanelGłównyLayout.setHorizontalGroup(
            ko_jPanelGłównyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ko_jPanelGłównyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ko_jPanelGłównyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ko_jPanelGłównyLayout.createSequentialGroup()
                        .addComponent(ko_jLabelPrzeliczanie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ko_jComboBoxPrzeliczanie, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ko_jPanelGłównyLayout.createSequentialGroup()
                        .addComponent(ko_jLabelJednostki)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ko_jTextFieldJednostka, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ko_jPanelGłównyLayout.createSequentialGroup()
                        .addComponent(ko_jLabelPrzeliczone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ko_jTextFieldPrzeliczone, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        ko_jPanelGłównyLayout.setVerticalGroup(
            ko_jPanelGłównyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ko_jPanelGłównyLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(ko_jPanelGłównyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ko_jLabelPrzeliczanie, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ko_jComboBoxPrzeliczanie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(ko_jPanelGłównyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ko_jLabelJednostki)
                    .addComponent(ko_jTextFieldJednostka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ko_jPanelGłównyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ko_jLabelPrzeliczone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ko_jTextFieldPrzeliczone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        ko_jMenuPlik.setText("Plik");

        ko_jMenuItemHistoria.setText("Pokaż historię");
        ko_jMenuItemHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_jMenuItemHistoriaActionPerformed(evt);
            }
        });
        ko_jMenuPlik.add(ko_jMenuItemHistoria);

        ko_jMenuItemZamknij.setText("Zamknij");
        ko_jMenuItemZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_jMenuItemZamknijActionPerformed(evt);
            }
        });
        ko_jMenuPlik.add(ko_jMenuItemZamknij);

        ko_jMenuBarMenu.add(ko_jMenuPlik);

        ko_jMenuProgram.setText("O programie");

        ko_jMenuItemProgram.setText("O programie");
        ko_jMenuItemProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ko_jMenuItemProgramActionPerformed(evt);
            }
        });
        ko_jMenuProgram.add(ko_jMenuItemProgram);

        ko_jMenuBarMenu.add(ko_jMenuProgram);

        setJMenuBar(ko_jMenuBarMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ko_jPanelGłówny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ko_jPanelGłówny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ko_jMenuItemProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_jMenuItemProgramActionPerformed
        JOptionPane.showMessageDialog(null, "Program przelicza jednostki");
    }//GEN-LAST:event_ko_jMenuItemProgramActionPerformed

    private void ko_jMenuItemZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_jMenuItemZamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ko_jMenuItemZamknijActionPerformed

    private void ko_jComboBoxPrzeliczanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_jComboBoxPrzeliczanieActionPerformed
        String jednostka = (String) ko_jComboBoxPrzeliczanie.getSelectedItem();
        if(jednostka.equals("Temperatura")){
            ko_jLabelJednostki.setText("Wprowadź wartość którą chcesz przeliczyć (kelwiny): ");
        }else{
            ko_jLabelJednostki.setText("Wprowadź wartość którą chcesz przeliczyć (metry): ");
        }
        if(jednostka.equals("Temperatura")){
            ko_jLabelPrzeliczone.setText("Przeliczona wartość (stopnie Celsjusza): ");
        }else{
            ko_jLabelPrzeliczone.setText("Przeliczona wartość (kilometry): ");
        }
    }//GEN-LAST:event_ko_jComboBoxPrzeliczanieActionPerformed

    private void ko_jTextFieldJednostkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_jTextFieldJednostkaActionPerformed
        String dane =("");
        String jednostka = (String) ko_jComboBoxPrzeliczanie.getSelectedItem();
        if(jednostka.equals("Temperatura")){
            String wpisane = ko_jTextFieldJednostka.getText();
            int kelwiny = Integer.parseInt(wpisane);
            double celsjusze = kelwiny-273;
            String tekst =String.valueOf(celsjusze);
            
            ko_jTextFieldPrzeliczone.setText(tekst);
            dane = "t;k= "+kelwiny+";c= "+celsjusze;
        }else{
            String wpisane = ko_jTextFieldJednostka.getText();
            double metry = Integer.parseInt(wpisane);
            double kilometry = metry/1000;
            String tekst =String.valueOf(kilometry);
            
            ko_jTextFieldPrzeliczone.setText(tekst);
            dane = "o;m= "+metry+";km= "+kilometry+"\n";
        }   
            
       
        
        
        File f = new File("przeliczanie.txt");
        try{
            FileWriter fw = new FileWriter(f,true);
            fw.write(dane+"\n");
            fw.close();
        } catch(IOException e){
            System.out.println("błąd: "+e.toString());
        }
    }//GEN-LAST:event_ko_jTextFieldJednostkaActionPerformed

    private void ko_jTextFieldPrzeliczoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_jTextFieldPrzeliczoneActionPerformed

    }//GEN-LAST:event_ko_jTextFieldPrzeliczoneActionPerformed

    private void ko_jMenuItemHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ko_jMenuItemHistoriaActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showDialog(this,"Wybierz plik");

        try {
            String text ="";
            File f = jFileChooser.getSelectedFile();
            Scanner sc = new Scanner(f);
            while(sc.hasNext()){
                text = text+sc.nextLine()+"\n";
            }
            ko_jTextAreaOdczyt.setText(text);
        }catch (FileNotFoundException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_ko_jMenuItemHistoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZadanieKamilOciepa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZadanieKamilOciepa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZadanieKamilOciepa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZadanieKamilOciepa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZadanieKamilOciepa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> ko_jComboBoxPrzeliczanie;
    private javax.swing.JLabel ko_jLabelJednostki;
    private javax.swing.JLabel ko_jLabelPrzeliczanie;
    private javax.swing.JLabel ko_jLabelPrzeliczone;
    private javax.swing.JMenuBar ko_jMenuBarMenu;
    private javax.swing.JMenuItem ko_jMenuItemHistoria;
    private javax.swing.JMenuItem ko_jMenuItemProgram;
    private javax.swing.JMenuItem ko_jMenuItemZamknij;
    private javax.swing.JMenu ko_jMenuPlik;
    private javax.swing.JMenu ko_jMenuProgram;
    private javax.swing.JPanel ko_jPanelGłówny;
    private javax.swing.JTextArea ko_jTextAreaOdczyt;
    private javax.swing.JTextField ko_jTextFieldJednostka;
    private javax.swing.JTextField ko_jTextFieldPrzeliczone;
    // End of variables declaration//GEN-END:variables
}
