/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.slowoliczator;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author maciejkolpaczek
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        wczytywanie();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainJP = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuP = new javax.swing.JMenu();
        jMenuItemZ = new javax.swing.JMenuItem();
        jMenuItemW = new javax.swing.JMenuItem();
        jMenuItemL = new javax.swing.JMenuItem();
        jMenuE = new javax.swing.JMenu();
        jMenuItemAB = new javax.swing.JMenuItem();
        jMenuItemDB = new javax.swing.JMenuItem();
        jMenuK = new javax.swing.JMenu();
        jMenuItemNiebieski = new javax.swing.JMenuItem();
        jMenuItemZielony = new javax.swing.JMenuItem();
        jMenuItemRóżowy = new javax.swing.JMenuItem();
        jMenuItemCzerwony = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainJP.setBackground(new java.awt.Color(134, 252, 121));

        jPanel1.setBackground(new java.awt.Color(134, 252, 121));
        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("SPRAWDZ!!!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainJPLayout = new javax.swing.GroupLayout(MainJP);
        MainJP.setLayout(MainJPLayout);
        MainJPLayout.setHorizontalGroup(
            MainJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainJPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainJPLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(MainJPLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jButton1)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        MainJPLayout.setVerticalGroup(
            MainJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainJPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jMenuP.setText("Plik");

        jMenuItemZ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemZ.setText("Zapisz");
        jMenuP.add(jMenuItemZ);

        jMenuItemW.setText("Wczytaj");
        jMenuP.add(jMenuItemW);

        jMenuItemL.setText("Zapisz wyglad");
        jMenuItemL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLActionPerformed(evt);
            }
        });
        jMenuP.add(jMenuItemL);

        jMenuBar.add(jMenuP);

        jMenuE.setText("Edytuj");

        jMenuItemAB.setText("Dodanie przycisku");
        jMenuItemAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemABActionPerformed(evt);
            }
        });
        jMenuE.add(jMenuItemAB);

        jMenuItemDB.setText("Usuniecie przycisku");
        jMenuE.add(jMenuItemDB);

        jMenuBar.add(jMenuE);

        jMenuK.setText("Kolor");

        jMenuItemNiebieski.setText("Niebieski");
        jMenuItemNiebieski.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNiebieskiActionPerformed(evt);
            }
        });
        jMenuK.add(jMenuItemNiebieski);

        jMenuItemZielony.setText("Zielony");
        jMenuItemZielony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemZielonyActionPerformed(evt);
            }
        });
        jMenuK.add(jMenuItemZielony);

        jMenuItemRóżowy.setText("Różowy");
        jMenuItemRóżowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRóżowyActionPerformed(evt);
            }
        });
        jMenuK.add(jMenuItemRóżowy);

        jMenuItemCzerwony.setText("Czerwony");
        jMenuItemCzerwony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCzerwonyActionPerformed(evt);
            }
        });
        jMenuK.add(jMenuItemCzerwony);

        jMenuBar.add(jMenuK);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemABActionPerformed
        JButton button = new JButton("Wyłącz program");
        jPanel1.add(button);
        jPanel1.revalidate();
        jMenuItemAB.setEnabled(false);
    }//GEN-LAST:event_jMenuItemABActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String tekst = jTextArea1.getText();
        String[] podzielony = tekst.trim().split("\\s+");
        int iloscslow = podzielony.length;
        System.out.println(iloscslow);
        JOptionPane.showMessageDialog(null, "Ilość słów: "+iloscslow);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemNiebieskiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNiebieskiActionPerformed
        MainJP.setBackground(new java.awt.Color(121, 145, 252));
        jPanel1.setBackground(new java.awt.Color(121, 145, 252));
        color = "121, 145, 252";
    }//GEN-LAST:event_jMenuItemNiebieskiActionPerformed

    private void jMenuItemZielonyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemZielonyActionPerformed
        MainJP.setBackground(new java.awt.Color(134, 252, 121));
        jPanel1.setBackground(new java.awt.Color(134, 252, 121));
        color = "134, 252, 121";
    }//GEN-LAST:event_jMenuItemZielonyActionPerformed

    private void jMenuItemCzerwonyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCzerwonyActionPerformed
        MainJP.setBackground(new java.awt.Color(247, 25, 25));
        jPanel1.setBackground(new java.awt.Color(247, 25, 25));
        color = "247, 25, 25";
    }//GEN-LAST:event_jMenuItemCzerwonyActionPerformed

    private void jMenuItemRóżowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRóżowyActionPerformed
        MainJP.setBackground(new java.awt.Color(247, 104, 228));
        jPanel1.setBackground(new java.awt.Color(247, 104, 228)); 
        color = "247, 104, 228";
    }//GEN-LAST:event_jMenuItemRóżowyActionPerformed

    private void jMenuItemLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLActionPerformed
        try {
            FileWriter myWriter = new FileWriter("color.txt");
            myWriter.write(color);
            myWriter.close();
            System.out.println("Successfully wrote to the file.");
        } catch (IOException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemLActionPerformed
    public void wczytywanie(){
        try {
            File myObj = new File("color.txt");
            Scanner myReader = new Scanner(myObj);
        while (myReader.hasNextLine()) {
            color = myReader.nextLine();
            System.out.println(color);
        }
        myReader.close();
        } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
        String[] podzielone = color.split(", ");
        int R = Integer.parseInt(podzielone[0]);
        int G = Integer.parseInt(podzielone[1]);
        int B = Integer.parseInt(podzielone[2]);
        MainJP.setBackground(new java.awt.Color(R,G,B));
        jPanel1.setBackground(new java.awt.Color(R,G,B));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    String color;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainJP;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuE;
    private javax.swing.JMenuItem jMenuItemAB;
    private javax.swing.JMenuItem jMenuItemCzerwony;
    private javax.swing.JMenuItem jMenuItemDB;
    private javax.swing.JMenuItem jMenuItemL;
    private javax.swing.JMenuItem jMenuItemNiebieski;
    private javax.swing.JMenuItem jMenuItemRóżowy;
    private javax.swing.JMenuItem jMenuItemW;
    private javax.swing.JMenuItem jMenuItemZ;
    private javax.swing.JMenuItem jMenuItemZielony;
    private javax.swing.JMenu jMenuK;
    private javax.swing.JMenu jMenuP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
